/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.jsonc --env=production --include-runtime=false --strict-vars=false worker/src/worker-configuration.d.ts` (hash: a636f8ac58c2b33a25cb2310807ef1ad)
interface __BaseEnv_Env {
  DB: D1Database;
  ENVIRONMENT: string;
  ALLOWED_ORIGINS: string;
  TURNSTILE_EXPECTED_HOSTNAME: string;
  TURNSTILE_VERIFY_URL: string;
  EMAILJS_SEND_URL: string;
  EMAILJS_ORIGIN: string;
  ACCESS_TEAM_DOMAIN: string;
  ACCESS_AUD: string;
  TURNSTILE_SECRET: string;
  EMAILJS_SERVICE_ID: string;
  EMAILJS_TEMPLATE_ID: string;
  EMAILJS_PUBLIC_KEY: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "ENVIRONMENT"
        | "ALLOWED_ORIGINS"
        | "TURNSTILE_EXPECTED_HOSTNAME"
        | "TURNSTILE_VERIFY_URL"
        | "EMAILJS_SEND_URL"
        | "EMAILJS_ORIGIN"
        | "ACCESS_TEAM_DOMAIN"
        | "ACCESS_AUD"
        | "TURNSTILE_SECRET"
        | "EMAILJS_SERVICE_ID"
        | "EMAILJS_TEMPLATE_ID"
        | "EMAILJS_PUBLIC_KEY"
      >
    > {}
}
